blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/atInisiatifZakat/laravel-budget/discussions/new?category=question
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/atInisiatifZakat/laravel-budget/discussions/new?category=enhancement
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/atInisiatifZakat/laravel-budget/security/policy
    about: Learn how to notify us for sensitive bugs
  - name: Report a bug
    url: https://github.com/atInisiatifZakat/laravel-budget/issues/new
    about: Report a reproducible bug
